# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
  app.artykul_repository:
    class: AppBundle\Repository\Doctrine\ArtykulRepository
    arguments: ['@doctrine.orm.entity_manager']

  app.artykul_controller:
    class: AppBundle\Controller\ArtykulController
    arguments: ['@app.artykul_repository']
    calls:
      - [ setContainer, [ '@service_container' ]]