# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.artykul_repository:
        class: AppBundle\Repository\Doctrine\ArtykulRepository
        arguments: ['@doctrine.orm.entity_manager']

    app.onas_controller:
        class: AppBundle\Controller\ONasController
        arguments: ['@app.artykul_repository']